name: OptEcoPrime
version: @version@
main: com.playernguyen.optecoprime.OptEcoPrime
authors: [ Player_Nguyen ]
description: Powerful point system for Minecraft Bukkit server
softdepend: [ PlaceholderAPI, ShopGUIPlus, BossShopPro ]