# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle build and test (CI)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 10, 12, 14 ]
    env:
      # Database section of the environment
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK {{matrix.jdk}}
        uses: actions/setup-java@v2
        with:
          java-version: {{matrix.jdk}}
          distribution: 'adopt'
      - name: Setup MySQL database server
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --scan
      - name: Run testing with Gradle
        run: ./gradlew test --info
